'use strict';
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = (name, cls='') => `<i data-lucide="${name}" class="${cls}"></i>`;
const profiles = {modern:{minecraft:'1.21.1',loader:'neoforge',loaderVersion:'21.1.250',javaMajor:21},legacy:{minecraft:'1.12.1',loader:'forge',loaderVersion:'14.22.1.2485',javaMajor:8}};
let S = {version:'1.1.0',settings:{ram:6,javaPath:'',jvmPreset:'balanced',serverHost:'revolution.modpack.gg',serverPort:25565,manifestUrl:'',discordUrl:'https://discord.com/invite/R3bDcSBv52',mapUrl:'',websiteUrl:'',maintenanceUrl:'',newsUrl:'',microsoftClientId:'',discordClientId:'',rpcEnabled:true,reducedMotion:false,autoConnect:true,account:{name:'Revolution',type:'offline'},instances:[{id:'revolution',name:'Revolution Modded',profile:'modern',hours:0}]},profile:profiles.modern,profiles,instance:{id:'revolution',name:'Revolution Modded',profile:'modern',hours:0},job:{busy:false,phase:'idle',message:'Готові до нової пригоди',current:0,total:0,error:''},server:{state:'checking',online:null,max:null,ping:null},integrity:{state:'local',total:0},mods:[],java:null,rpc:'unconfigured',news:[],events:[],running:false};
let page='home', settingsTab='game', modFilter='all', modSearch='', lastSignature='', connected=false, polling=false, lastError='', lastJobBusy=false;
const titles={home:['РАДІ БАЧИТИ ТЕБЕ ЗНОВУ','Твоя наступна пригода.'],instances:['УСІ ТВОЇ СВІТИ ПОРУЧ','Мої збірки'],mods:['ТВІЙ СВІТ. ТВОЇ МОЖЛИВОСТІ.','Моди збірки'],downloads:['УСЕ ПІД КОНТРОЛЕМ','Завантаження'],news:['ТЕ, ЩО НАС ОБ’ЄДНУЄ','Життя Revolution'],logs:['ПОДІЇ ТА ДІАГНОСТИКА','Журнал і помічник'],settings:['ЗРОБИ ЙОГО СВОЇМ','Налаштування']};
const statusNames={online:'Онлайн',offline:'Недоступний',maintenance:'Технічні роботи',checking:'Перевірка…',unconfigured:'Не підключено'};
const rpcNames={active:'Rich Presence активно',disconnected:'Discord не запущено',unconfigured:'Очікує підключення',disabled:'Вимкнено'};
const loaderName=p=>p.loader==='neoforge'?'NeoForge':'Forge';
const icons=()=>window.lucide?.createIcons();
function toast(message,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;$('#toasts').append(el);setTimeout(()=>el.remove(),error?7500:4200);}
async function call(action,payload={}){
  if(!window.pywebview?.api){toast('Для цієї дії відкрийте настільний застосунок Revolution.exe.',true);return null;}
  try{const result=await window.pywebview.api.command(action,payload);if(!result.ok){toast(result.error,true);return null;}await poll();return result;}catch(e){toast('Не вдалося виконати дію. Перевірте журнал лаунчера.',true);return null;}
}
function go(next){if(!titles[next])next='home';page=next;lastSignature='';$('#page-title').textContent=titles[page][1];$('#page-eyebrow').textContent=titles[page][0];document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));render();$('main').scrollTop=0;}
function home(){
  const p=S.profile,s=S.server,j=S.job,integrity=S.integrity;
  const state=statusNames[s.state]||'Невідомо';
  const integrityText={local:S.mods.length?'Локальні моди':S.bundle?.available?'Модпак у комплекті':'Додай свою збірку',unchecked:'Очікує перевірки',healthy:'Усе синхронізовано',updates:'Знайдено оновлення',error:'Перевірка не завершена'}[integrity.state]||'Перевірка…';
  return `<section class="hero"><div class="hero-bg"></div><div class="hero-top"><span class="badge coral">${icon('sparkles')} ТВОЯ СПІЛЬНОТА. ТВІЙ СВІТ.</span><span class="hero-number">EST. REVOLUTION / 01</span></div><div class="hero-copy"><h2>REVOLUTION<span>MODDED</span></h2><p>Знайомий світ. Безмежні можливості.<br>Твори власну історію разом із нашою спільнотою.</p></div><span class="hero-caption">A WORLD WORTH EXPLORING</span><div class="hero-bottom"><div class="version-pills"><span class="pill">${icon('box')} Minecraft ${esc(p.minecraft)}</span><span class="pill">${icon('anvil')} ${loaderName(p)} ${esc(p.loaderVersion)}</span></div><div class="play-cluster"><button class="play-button" data-action="launch" ${j.busy||S.running?'disabled':''}>${icon(S.running?'check':j.busy?'loader-circle':'play')} ${S.running?'Гра запущена':j.busy?'Готуємо гру…':'Почати гру'}</button><button class="play-extra" data-page="instances" title="Вибрати збірку">${icon('chevron-down')}</button></div></div></section>
  ${j.busy||j.error?`<div class="inline-job">${icon(j.error?'circle-alert':'loader-circle',j.busy?'spin':'')}<span>${esc(j.error||j.message)}</span><button data-page="downloads">Докладніше</button></div>`:''}
  <div class="section-row"><h3>Усе готове до пригод?</h3><button class="text-button" data-action="refresh_server">${icon('refresh-cw')} Оновити статус</button></div>
  <div class="status-grid"><div class="status-card"><div class="card-label">${icon('server')} Сервер Revolution <span class="status-badge right ${esc(s.state)}"><span class="dot ${esc(s.state)}"></span>${state}</span></div><div class="card-main"><strong>${s.online===null||s.online===undefined?'—':esc(s.online)} <span class="unit">/ ${s.max===null||s.max===undefined?'—':esc(s.max)}</span></strong><span class="unit">гравців</span></div><div class="card-detail"><span>${esc(S.settings.serverHost||'Додайте адресу сервера')}</span><span>${s.ping===null||s.ping===undefined?'— ms':esc(s.ping)+' ms'}</span></div></div>
  <div class="status-card"><div class="card-label">${icon('shield-check')} Стан модпаку <span class="dot right ${esc(integrity.state)}"></span></div><div class="card-main"><strong class="status-text">${integrityText}</strong></div><div class="card-detail"><span>${S.mods.length?S.mods.length+' файлів модів':S.bundle?.available?S.bundle.total+' файлів готові до встановлення':'Маніфест ще не підключено'}</span><button class="text-button" data-page="mods">${icon('arrow-right')}</button></div></div>
  <div class="status-card"><div class="card-label">${icon('radio')} Discord Rich Presence <span class="dot right ${esc(S.rpc)}"></span></div><div class="card-main"><strong class="status-text">${S.rpc==='active'?(S.running?'У грі на Revolution':'Ти на зв’язку'):S.rpc==='disabled'?'Вимкнено':'Підключімо Discord'}</strong></div><div class="card-detail"><span>${rpcNames[S.rpc]}</span><button class="text-button" data-settings="integrations">${icon('arrow-right')}</button></div></div></div>
  <div class="section-row"><h3>Revolution — більше, ніж гра</h3><button class="text-button" data-page="news">Життя спільноти ${icon('arrow-right')}</button></div>
  <div class="quick-grid"><button class="quick-card discord-card" data-link="discordUrl"><span class="quick-icon">${icon('messages-square')}</span><div><strong>Твої люди вже тут</strong><p>Спілкуйся та знаходь друзів у Discord</p></div>${icon('arrow-up-right')}</button><button class="quick-card map" data-link="mapUrl"><span class="quick-icon">${icon('map')}</span><div><strong>Світ як на долоні</strong><p>Відкрити онлайн-карту</p></div>${icon('arrow-up-right')}</button><button class="quick-card site" data-link="websiteUrl"><span class="quick-icon">${icon('globe')}</span><div><strong>Усе про Revolution</strong><p>Наш сайт і корисні посилання</p></div>${icon('arrow-up-right')}</button></div>`;
}
function instances(){return `<div class="toolbar"><p class="muted">Окремий простір для кожної пригоди.</p><button class="btn primary" data-modal="instance">${icon('plus')} Створити збірку</button></div><div class="instance-grid">${S.settings.instances.map(x=>{const p={...S.profiles[x.profile],...(x.loaderVersion?{loaderVersion:x.loaderVersion}:{})},active=x.id===S.instance.id;return `<article class="instance-card ${active?'selected':''}"><div class="instance-art"><span class="badge">${active?'АКТИВНА ЗБІРКА':x.profile==='legacy'?'LEGACY EDITION':'JAVA EDITION'}</span><span class="instance-icon">${icon('box')}</span></div><div class="instance-body"><h3>${esc(x.name)}</h3><div class="instance-meta"><span>Minecraft ${esc(p.minecraft)}</span><span>${loaderName(p)} ${esc(p.loaderVersion)}</span></div><div class="instance-actions"><button class="btn ${active?'primary':''}" data-switch="${esc(x.id)}">${icon(active?'check':'play')} ${active?'Обрано':'Обрати збірку'}</button>${active?`<button class="btn" data-action="open_folder" title="Папка збірки">${icon('folder-open')}</button>`:''}</div><div class="card-detail"><span>${x.profile==='modern'?'Java 21':'Java 8'} · Ізольований інстанс</span><span>${Number(x.hours||0).toFixed(1)} год у грі</span></div></div></article>`;}).join('')}</div><div class="info-line neutral">${icon('folders')} Кожна збірка має власні моди, конфігурації, світи та бібліотеки. Перемикання доступне після закриття гри.</div>`;}
function mods(){
  const filtered=S.mods.filter(m=>(modFilter==='all'||m.source===modFilter)&&(m.name+' '+m.file).toLowerCase().includes(modSearch.toLowerCase()));
  return `${updateCard()}${S.bundle?.available?`<div class="panel" style="margin-bottom:20px"><div class="toolbar" style="margin-bottom:0"><div><h3>Твій модпак уже тут</h3><p class="muted">${S.bundle.total} файлів у комплекті · встановлення та відновлення з перевіркою SHA-256.</p></div><button class="btn primary" data-action="sync" ${S.job.busy||S.running?'disabled':''}>${icon('package-check')} ${S.mods.length?'Відновити модпак':'Встановити модпак'}</button></div></div>`:''}<div class="toolbar"><div class="left"><div class="search">${icon('search')}<input id="mod-search" type="search" placeholder="Знайти мод у збірці…" value="${esc(modSearch)}" aria-label="Пошук модів"></div></div><div class="left"><button class="btn" data-action="open_folder">${icon('folder-open')} Папка</button><button class="btn primary" data-action="import_mods">${icon('plus')} Додати моди</button></div></div><div class="toolbar"><div class="chips"><button class="chip ${modFilter==='all'?'active':''}" data-filter="all">Усі моди · ${S.mods.length}</button><button class="chip ${modFilter==='modrinth'?'active':''}" data-filter="modrinth">Modrinth</button><button class="chip ${modFilter==='curseforge'?'active':''}" data-filter="curseforge">CurseForge</button><button class="chip ${modFilter==='local'?'active':''}" data-filter="local">Локальні</button><button class="chip ${modFilter==='bundle'?'active':''}" data-filter="bundle">Комплект Revolution</button></div><button class="text-button" data-action="check">${icon('shield-check')} Перевірити цілісність</button></div>
  ${filtered.length?`<div class="panel" style="padding:5px 10px"><table class="mods-table"><thead><tr><th>МОД</th><th>ДЖЕРЕЛО</th><th>РОЗМІР</th></tr></thead><tbody>${filtered.map(m=>`<tr><td><div class="mod-title"><span>${icon('box')}</span><div><strong>${esc(m.name)}</strong><small>${esc(m.file)}</small></div></div></td><td>${esc({bundle:'Комплект Revolution',local:'Локальний файл',manifest:'Маніфест',modrinth:'Modrinth',curseforge:'CurseForge'}[m.source]||m.source)}</td><td>${(m.size/1048576).toFixed(2)} MB</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><div class="empty-symbol">${icon('blocks')}</div><h3>${S.mods.length?'Нічого не знайдено':'Твій світ починається з модів'}</h3><p>${S.mods.length?'Спробуй іншу назву або зміни фільтр.':'Додай JAR-файли збірки Revolution або підключи маніфест сервера, щоб отримувати перевірені оновлення.'}</p><div class="actions"><button class="btn primary" data-action="import_mods">${icon('plus')} Імпортувати моди</button><button class="btn" data-settings="community">Підключити маніфест ${icon('arrow-right')}</button></div></div>`}
  <div class="section-row"><h3>Керування збіркою</h3></div><div class="panel"><div class="toolbar" style="margin-bottom:0"><div><h3>${S.bundle?.available?'Відновлення з комплекту':'Оновлення під контролем сервера'}</h3><p class="muted">Зафіксовані версії, SHA-256 і відкат у разі помилки.</p></div><button class="btn" data-action="sync">${icon('refresh-cw')} Відновити цілісність</button></div></div><div class="info-line neutral">${icon('info')} Локальні моди мають відповідати ${loaderName(S.profile)} і Minecraft ${esc(S.profile.minecraft)}. Локальні додатки залишаються під твоїм контролем; релізи сервера містять затверджені залежності.</div>`;
}
function downloads(){const j=S.job;const percent=j.total?Math.min(100,Math.max(0,Math.round(j.current/j.total*100))):0;return `<div class="panel job-card"><div class="job-head"><span class="job-icon">${icon(j.error?'circle-alert':j.busy?'download':j.phase==='done'?'circle-check':'hard-drive-download',j.busy?'spin':'')}</span><div><h3>${esc(j.message)}</h3><p>${j.error?esc(j.error):j.busy?'Залишай лаунчер відкритим — ми все підготуємо.':'Оновлення та встановлення з’являтимуться тут.'}</p></div>${j.busy?'<button class="btn" data-action="cancel">Скасувати</button>':'<button class="btn" data-action="check">Перевірити збірку</button>'}</div><div class="progress-track"><div class="progress-fill ${j.busy?'busy':''} ${j.busy&&!j.total?'indeterminate':''}" style="width:${percent}%"></div></div><div class="progress-detail"><span>${esc(S.instance.name)}</span><span>${j.busy?(j.total?percent+'%':'Обробка…'):j.phase==='done'?'Завершено':'Очікування'}</span></div><div class="steps"><span>${icon('coffee')} Java</span><span>${icon('box')} Minecraft</span><span>${icon('blocks')} Модпак</span><span>${icon('shield-check')} Перевірка</span><span>${icon('play')} Запуск</span></div></div>${updateCard()}<div class="section-row"><h3>Останні події</h3><button class="text-button" data-page="logs">Повний журнал ${icon('arrow-right')}</button></div>${consoleHtml(S.events.slice(-12))}<div class="info-line neutral">${icon('shield-check')} Оновлення модпаку застосовуються після перевірки всіх завантажених файлів. Пошкоджений файл не замінить робочий.</div>`;}
function consoleHtml(entries){return `<div class="console" aria-label="Журнал подій">${entries.length?entries.map(e=>`<div class="log-entry"><span class="log-time">${esc(e.time)}</span><span class="log-level ${esc(e.level)}">${esc(e.level.toUpperCase())}</span><span class="log-message">${esc(e.message)}</span></div>`).join(''):'<span class="log-time">Журнал поки порожній. Тут з’являться події встановлення та запуску.</span>'}</div>`;}
function logs(){return `<div class="toolbar"><p class="muted">Події поточного сеансу. Файли журналів зберігаються на диску.</p><button class="btn" data-logs="true">${icon('folder-open')} Відкрити журнали</button></div>${diagnosisHtml()}${consoleHtml(S.events)}<div class="info-line neutral">${icon('terminal')} Журнали Minecraft доступні для діагностики. Основний журнал зберігається у папці активної збірки: logs/revolution-game.log.</div><button class="btn" data-action="open_folder" style="margin-top:18px">${icon('folder-open')} Папка активної збірки</button>`;}
function news(){return `<div class="news-grid"><article class="news-card featured"><span class="badge coral">СПІЛЬНОТА REVOLUTION</span><h3>Найкращі історії<br>ми створюємо разом.</h3><p>Знайди команду для нової бази, покажи свою останню споруду або просто зазирни привітатися.</p><button class="btn primary" data-link="discordUrl">Відкрити Discord ${icon('arrow-up-right')}</button></article><article class="news-card"><span class="badge">ТВІЙ ЛАУНЧЕР</span><h3>Усе для наступного<br>великого задуму.</h3><p>Minecraft ${esc(S.profile.minecraft)}, ${loaderName(S.profile)} та твої улюблені моди. Почни з імпорту збірки — пригоди зачекають лише мить.</p><button class="btn" data-page="mods">Перейти до модів ${icon('arrow-right')}</button></article>${S.news.map(n=>`<article class="news-card"><small>${esc(n.date)}</small><h3>${esc(n.title)}</h3>${n.url?`<button class="text-button" data-news="${esc(n.url)}">Читати новину ${icon('arrow-up-right')}</button>`:''}</article>`).join('')}</div>${!S.news.length?`<div class="info-line neutral">${icon('rss')} Підключіть RSS або Atom у налаштуваннях спільноти, щоб бачити актуальні новини та патчноути тут.<button class="text-button" data-settings="community">Налаштувати ${icon('arrow-right')}</button></div>`:''}`;}
function field(key,label,placeholder='',type='text',hint=''){return `<div class="field"><label for="set-${key}">${label}</label><input id="set-${key}" name="${key}" type="${type}" value="${esc(S.settings[key]??'')}" placeholder="${esc(placeholder)}" ${type==='number'?'min="1" max="65535"':''}>${hint?`<small>${hint}</small>`:''}</div>`;}
function toggle(key,label,hint){return `<label class="toggle-row"><span><strong>${label}</strong><small>${hint}</small></span><input type="checkbox" class="switch" name="${key}" ${S.settings[key]?'checked':''} aria-label="${label}"></label>`;}
function settings(){let content='';if(settingsTab==='game')content=`<div class="settings-grid"><section class="panel"><h3>Оперативна пам’ять</h3><p>Залиш трохи ресурсів для системи.</p><div class="field" style="margin-top:24px"><div class="range-head"><label for="set-ram">Виділено для Minecraft</label><strong><span id="ram-value">${S.settings.ram}</span> <small>ГБ</small></strong></div><input id="set-ram" name="ram" type="range" min="2" max="32" step="1" value="${S.settings.ram}"><div class="range-labels"><span>2 ГБ</span><span>16 ГБ</span><span>32 ГБ</span></div></div><div class="field"><label for="set-jvmPreset">Пресет JVM</label><select id="set-jvmPreset" name="jvmPreset"><option value="balanced" ${S.settings.jvmPreset==='balanced'?'selected':''}>Збалансований · G1GC</option><option value="performance" ${S.settings.jvmPreset==='performance'?'selected':''}>Продуктивність · G1GC, коротші паузи</option></select><small>6–8 ГБ — початкова рекомендація для середньої збірки. Враховуй загальний обсяг RAM.</small></div></section><section class="panel"><h3>Середовище Java</h3><p>Потрібна Java ${S.profile.javaMajor} · 64-bit</p><div class="info-line neutral" style="margin-bottom:22px">${icon('coffee')} ${S.java?'Знайдено Java '+esc(S.java.major):'Java буде знайдена або завантажена автоматично.'}</div><div class="field"><label for="set-javaPath">Власний шлях до Java (необов’язково)</label><div class="row"><input id="set-javaPath" name="javaPath" value="${esc(S.settings.javaPath)}" placeholder="Автоматичний вибір"><button class="btn" type="button" data-action="pick_java" title="Обрати Java">${icon('folder-open')}</button></div><small>Порожнє поле вмикає автоматичне керування Eclipse Temurin.</small></div><button class="btn" type="button" data-action="java">${icon('download')} Підготувати Java ${S.profile.javaMajor}</button></section></div><div class="panel">${toggle('autoConnect','Одразу на Revolution','Автоматично підключатися до сервера після запуску Minecraft.')}${toggle('reducedMotion','Зменшити анімації','Вимкнути рух фону, пульсацію та переходи між екранами.')}</div>`;
  if(settingsTab==='community')content=`<div class="settings-grid"><section class="panel"><h3>Сервер та оновлення</h3><p style="margin-bottom:22px">Підключення до спільноти Revolution.</p>${field('serverHost','Адреса сервера','revolution.modpack.gg')}${field('serverPort','Порт сервера','','number','25565: нестандартний порт визначається через DNS SRV.')}${field('manifestUrl','Маніфест модпаку','https://cdn.example.org/revolution/manifest.json','url','Лаунчер перевіряє версії, SHA-256 та оновлює лише керовані файли.')}${field('manifestPublicKey','Публічний ключ каналу','Ed25519 · Base64','text','Постачається адміністратором разом із посиланням.')}${field('maintenanceUrl','Статус технічних робіт','https://example.org/status.json','url','Необов’язковий JSON endpoint: {"maintenance": true}.')}</section><section class="panel"><h3>Посилання спільноти</h3><p style="margin-bottom:22px">Завжди на відстані одного кліку.</p>${field('discordUrl','Discord','https://discord.com/invite/...','url')}${field('mapUrl','Карта світу · Dynmap / Squaremap','https://map.example.org','url')}${field('websiteUrl','Сайт спільноти','https://example.org','url')}${field('newsUrl','Новини · RSS / Atom','https://example.org/feed.xml','url')}</section></div><div class="panel"><div class="toolbar" style="margin-bottom:0"><div><h3>Маніфест із твоєї збірки</h3><p class="muted">Згенеруй список модів та конфігурацій із контрольними сумами.</p></div><button type="button" class="btn" data-modal="manifest">${icon('file-json')} Створити manifest.json</button></div></div>`;
  if(settingsTab==='integrations')content=`<div class="settings-grid"><section class="panel"><h3>Microsoft</h3><p style="margin-bottom:22px">Офіційний вхід через системний браузер.</p>${field('microsoftClientId','Application (client) ID','xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx','text','Власний public-client застосунок із доступом до Minecraft API.')}<div class="info-line neutral">${icon('lock-keyhole')} OAuth із PKCE та перевіркою state. Refresh token зберігається у системному сховищі облікових даних.</div><div class="path-label">Redirect URI: http://localhost:59174/callback</div></section><section class="panel"><h3>Discord Rich Presence</h3><p style="margin-bottom:22px">Покажи друзям, де проходить твоя пригода.</p>${field('discordClientId','Discord Application ID','Application ID із Discord Developer Portal')}${toggle('rpcEnabled','Показувати активність','Потрібен запущений Discord Desktop і власний Application ID.')}<div class="card-detail" style="margin-top:20px"><span>Поточний стан</span><span>${rpcNames[S.rpc]}</span></div></section><section class="panel wide"><h3>Modrinth & CurseForge</h3><p style="margin-bottom:22px">Джерела та точні версії задаються у маніфесті сервера. Залежності включаються до цього ж списку.</p><div class="field"><label for="set-curseforgeKey">CurseForge API key</label><input id="set-curseforgeKey" name="curseforgeKey" type="password" placeholder="Ввести або замінити ключ" autocomplete="off"><small>Ключ зберігається в Windows Credential Manager. Порожнє поле залишає збережений ключ. Modrinth не потребує ключа.</small></div></section></div>`;
  if(settingsTab==='assistant')content=assistantSettings();
  if(settingsTab==='about')content=`<div class="panel"><img src="assets/mark.svg" width="60" height="60" alt="Revolution" style="margin-bottom:20px"><h3 style="font-size:23px">Revolution Launcher</h3><p>Версія ${esc(S.version)} · Open Source · MIT</p><p style="margin-top:20px">Створений для спільноти Revolution. Python, Qt WebEngine та minecraft-launcher-lib.<br>Неофіційний застосунок, не пов’язаний із Mojang або Microsoft.</p><div class="path-label">Дані: ${esc(S.dataDir||'Завантаження…')}</div><button type="button" class="btn" data-action="open_folder" style="margin-top:22px">${icon('folder-open')} Відкрити активну збірку</button></div>`;
  return `<div class="settings-tabs">${[['game','Гра та Java'],['community','Спільнота'],['integrations','Інтеграції'],['assistant','Помічник'],['about','Про лаунчер']].map(([id,label])=>`<button class="${settingsTab===id?'active':''}" data-tab="${id}">${label}</button>`).join('')}</div><form id="settings-form">${content}${settingsTab!=='about'?'<div class="settings-save"><small>Зміни набудуть чинності після збереження</small><button class="btn primary" type="submit">Зберегти налаштування</button></div>':''}</form>`;
}
const renderers={home,instances,mods,downloads,news,logs,settings};
function render(){const old=$('#page-content');old.innerHTML=renderers[page]();icons();document.body.classList.toggle('reduce-motion',!!S.settings.reducedMotion);}
function modal(type){let title='',body='';if(type==='account'){title='Твій профіль';body=`<p class="muted">Обери, як вирушити у світ Revolution.</p><button class="btn full" data-action="login"><span class="ms-grid"><span></span><span></span><span></span><span></span></span> Увійти через Microsoft</button><div class="modal-divider">або локальний профіль</div><form id="account-form"><div class="field"><label for="nickname">Ім’я у грі</label><input id="nickname" name="name" value="${esc(S.settings.account.name)}" pattern="[A-Za-z0-9_]{3,16}" minlength="3" maxlength="16" required autocomplete="off"><small>3–16 латинських літер, цифр або символів _</small></div><button class="btn primary full" type="submit">Зберегти профіль ${icon('arrow-right')}</button></form><p class="modal-foot">Локальний профіль працює в одиночній грі та на серверах, які дозволяють офлайн-вхід. Офіційні сервери потребують Microsoft-акаунту з Minecraft Java.</p>`;}
  if(type==='instance'){title='Нова пригода';body=`<p class="muted">Окрема збірка зі своїми модами, світами та налаштуваннями гри.</p><form id="instance-form"><div class="field"><label for="instance-name">Назва збірки</label><input id="instance-name" name="name" placeholder="Мій новий світ" maxlength="60" required></div><div class="field"><label for="instance-profile">Профіль гри</label><select id="instance-profile" name="profile"><option value="modern">Minecraft 1.21.1 · NeoForge 21.1.250</option><option value="legacy">Minecraft 1.12.1 · Forge 14.22.1.2485</option></select></div><button type="submit" class="btn primary full">${icon('plus')} Створити збірку</button></form>`;}
  if(type==='manifest'){title='Маніфест збірки';body=`<p class="muted">Згенеруємо SHA-256 для модів і конфігурацій активної збірки. Це чернетка для адміністратора. Для каналу оновлень підпиши її інструментом release_tool із вихідного коду.</p><form id="manifest-form"><div class="field"><label for="cdn-base">Базова адреса файлів на хостингу</label><input id="cdn-base" name="baseUrl" type="url" placeholder="https://cdn.example.org/revolution" required><small>Структура папок зберігається: /mods, /config та інші папки збірки.</small></div><div class="info-line neutral" style="margin-bottom:20px">${icon('info')} Файли з preserve: true у папках конфігурації не перезаписуються після першого встановлення.</div><button class="btn primary full" type="submit">${icon('file-json')} Згенерувати та зберегти</button></form>`;}
  if(type==='diagnostic-report'){title='Звіт для аналізу';body=reportModal();}
  $('#modal-content').innerHTML=`<div class="modal-head"><h3>${title}</h3><button class="icon-button" data-dismiss="true" aria-label="Закрити вікно">${icon('x')}</button></div><div class="modal-body">${body}</div>`;icons();$('#modal').showModal();}
async function poll(){if(!window.pywebview?.api||polling)return;polling=true;try{S=await window.pywebview.api.snapshot();connected=true;$('#bridge-status').textContent='Лаунчер підключено';$('#sidebar-name').textContent=S.settings.account.name;$('#account-kind').textContent=S.settings.account.type==='microsoft'?'Microsoft-акаунт':'Локальний профіль';document.querySelectorAll('.avatar').forEach(el=>el.textContent=S.settings.account.name[0].toUpperCase());$('#instance-count').textContent=S.settings.instances.length;$('#activity-dot').hidden=!S.job.busy;document.body.classList.toggle('reduce-motion',!!S.settings.reducedMotion);const signature=JSON.stringify(page==='home'?[S.instance,S.profile,S.server,S.integrity,S.rpc,S.job.busy,S.job.error,S.running,S.mods.length,S.settings.serverHost,S.bundle]:page==='settings'?null:page==='mods'?[S.mods,S.instance,S.bundle,S.job.busy,S.running,S.updates]:page==='instances'?[S.settings.instances,S.instance]:page==='news'?S.news:[S.job,S.events,S.updates,S.diagnostics]);if(signature!==lastSignature&&page!=='settings'){lastSignature=signature;render();}if(S.job.error&&S.job.error!==lastError){toast(S.job.error,true);lastError=S.job.error;}if(!S.job.error)lastError='';if(lastJobBusy&&!S.job.busy&&!S.job.error)toast(S.job.message);lastJobBusy=S.job.busy;}catch(e){$('#bridge-status').textContent='З’єднання втрачено';}finally{polling=false;}}
document.addEventListener('click',async event=>{const el=event.target.closest('button,a');if(!el)return;if(el.getAttribute('href')==='#home'){event.preventDefault();go('home');return;}if(el.dataset.page){go(el.dataset.page);return;}if(el.dataset.settings){settingsTab=el.dataset.settings;go('settings');return;}if(el.dataset.tab){settingsTab=el.dataset.tab;render();return;}if(el.dataset.modal){modal(el.dataset.modal);return;}if(el.dataset.dismiss){$('#modal').close();return;}if(el.dataset.link){await call('open_link',{key:el.dataset.link});return;}if(el.dataset.news){await call('open_news',{url:el.dataset.news});return;}if(el.dataset.logs){await call('open_folder',{kind:'logs'});return;}if(el.dataset.switch){const r=await call('switch',{id:el.dataset.switch});if(r){go('instances');toast('Збірку обрано');}return;}if(el.dataset.filter){modFilter=el.dataset.filter;render();return;}if(el.dataset.action){const action=el.dataset.action;if(action==='login'){$('#modal').close();}const r=await call(action);if(r&&action==='pick_java'&&r.path)$('#set-javaPath').value=r.path;if(r&&action==='diagnose')go('logs');if(r&&action==='export_diagnostics'&&r.saved)toast('Очищений звіт збережено');if(r&&action==='import_mods'&&r.count)toast(`Додано модів: ${r.count}`);if(r&&['sync','check','java','login'].includes(action))go('downloads');}});
document.addEventListener('input',event=>{if(event.target.id==='set-ram')$('#ram-value').textContent=event.target.value;if(event.target.id==='mod-search'){const caret=event.target.selectionStart;modSearch=event.target.value;render();const inp=$('#mod-search');inp.focus();try{inp.setSelectionRange(caret,caret);}catch(e){}}});
document.addEventListener('submit',async event=>{event.preventDefault();const form=event.target;const payload=Object.fromEntries(new FormData(form));if(form.id==='settings-form'){for(const el of form.querySelectorAll('input[type=checkbox]'))payload[el.name]=el.checked;for(const key of ['ram','serverPort'])if(key in payload)payload[key]=Number(payload[key]);const r=await call('save_settings',payload);if(r){toast('Налаштування збережено');render();}}else{const action={"account-form":'offline',"instance-form":'create_instance',"manifest-form":'export_manifest'}[form.id];if(!action)return;const r=await call(action,payload);if(r){$('#modal').close();if(action==='create_instance')go('instances');toast(action==='export_manifest'?(r.cancelled?'Збереження скасовано':`Маніфест збережено · ${r.count} файлів`):'Готово');}}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const box=$('#modal').getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)$('#modal').close();}});
window.addEventListener('pywebviewready',async()=>{await poll();render();});
go('home');poll();setInterval(poll,1000);setTimeout(()=>{if(!connected)$('#bridge-status').textContent='Перегляд інтерфейсу';},2500);
