'use strict';
function updateCard() {
  if(S.instance.id!=='revolution') return '';
  const u=S.updates||{}, remote=!!S.settings.manifestUrl;
  const label={idle:'Очікує перевірки',checking:'Перевіряємо канал',updating:'Оновлюємо збірку',ready:'Збірка актуальна',available:'Доступні зміни',error:'Оновлення не завершено',cancelled:'Перевірку скасовано'}[u.state]||'Підготовка';
  const lists=[['added','Додано'],['changed','Оновлено'],['removed','Прибрано']];
  return `<section class="panel update-panel"><div class="toolbar"><div><span class="eyebrow">КАНАЛ REVOLUTION</span><h3>${esc(label)}</h3><p class="muted">${remote?'Перевірка на старті, кожні 15 хвилин і перед грою.':'97 модів у комплекті. Канал нових релізів ще не підключено.'}</p></div><button class="btn" data-action="sync" ${S.job.busy||S.running?'disabled':''}>${icon('refresh-cw')} Перевірити зараз</button></div><div class="release-meta"><span>${icon(u.signed?'badge-check':'package')} ${u.signed?'Підпис перевірено':remote?'Підписаний канал':u.source==='cached'?'Остання встановлена версія':'Локальний комплект'}</span><span>Версія: ${esc(u.installedVersion||'ще не встановлено')}</span><span>Перевірка: ${u.lastChecked?new Date(u.lastChecked*1000).toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'}):'—'}</span></div>${lists.some(([key])=>u[key]?.length)?`<details class="release-changes"><summary>Склад останньої зміни · ${lists.map(([key,label])=>label+': '+(u[key]?.length||0)).join(' · ')}</summary><div class="changes-grid">${lists.map(([key,label])=>`<div><h4>${label}</h4><ul>${(u[key]||[]).map(name=>`<li>${esc(name)}</li>`).join('')||'<li>—</li>'}</ul></div>`).join('')}</div></details>`:''}${u.notes?.length?`<ul class="release-notes">${u.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul>`:''}${S.running?'<p class="muted">Оновлення продовжаться після виходу з гри.</p>':''}</section>`;
}
function diagnosisHtml() {
  const d=S.diagnostics||{}, busy=S.job.busy||S.running;
  const actions={sync:['Відновити модпак','data-action="sync"'],check:['Перевірити збірку','data-action="check"'],java:['Підготувати Java','data-action="java"'],settings:['Налаштувати RAM / Java','data-settings="game"'],folder:['Папка збірки','data-action="open_folder"'],account:['Увійти в акаунт','data-modal="account"']};
  return `<section class="panel assistant-panel"><div class="toolbar"><div><span class="eyebrow">REVOLUTION ASSIST</span><h3>Розберімося з помилкою</h3><p class="muted">Локальна діагностика з доказами з твоїх журналів.</p></div><button class="btn primary" data-action="diagnose" ${busy?'disabled':''}>${icon('scan-line')} Перевірити логи</button></div>${!d.id?'<div class="assistant-empty">Після невдалого запуску тут автоматично з’явиться звіт. Також можна перевірити останні логи вручну.</div>':`<div class="diagnosis-grid">${d.findings?.length?d.findings.map(f=>`<article class="finding"><span class="badge">ЗБІГ У ЖУРНАЛІ</span><h4>${esc(f.title)}</h4><p>${esc(f.advice)}</p><pre>${esc(f.evidence)}</pre>${actions[f.action]?`<button class="btn" ${actions[f.action][1]} ${busy?'disabled':''}>${actions[f.action][0]} ${icon('arrow-right')}</button>`:''}</article>`).join(''):`<div class="assistant-empty">${d.hasLogs?'Типову причину не визначено. Переглянь звіт або попроси ШІ пояснити журнал.':'Журналів помилки ще немає. Запусти гру, щоб отримати дані для діагностики.'}</div>`}</div><div class="assistant-actions"><button class="btn" data-modal="diagnostic-report">${icon('file-search')} Переглянути звіт</button><button class="btn" data-action="export_diagnostics">${icon('download')} Зберегти звіт</button><button class="btn" data-modal="diagnostic-report" ${busy||!d.hasLogs?'disabled':''}>${icon('sparkles')} Пояснити з ШІ</button><button class="text-button" data-settings="assistant">Налаштування ШІ</button></div>${d.ai?.state==='working'?'<div class="info-line neutral">ШІ читає звіт… <button class="text-button" data-action="cancel">Скасувати</button></div>':''}${d.ai?.text?`<article class="ai-answer"><span class="badge">${d.ai.state==='error'?'СЕРВІС НЕДОСТУПНИЙ':'ПОЯСНЕННЯ ШІ · ПЕРЕВІР РЕКОМЕНДАЦІЇ'}</span><pre>${esc(d.ai.text)}</pre></article>`:''}`}</section>`;
}
function assistantSettings() {
  return `<section class="panel"><h3>Помічник із крашами</h3><p class="muted">Локальна діагностика працює без ШІ. Для пояснень обери власний сервіс.</p><div class="settings-grid assistant-config"><div><div class="field"><label for="set-aiProvider">Сервіс</label><select id="set-aiProvider" name="aiProvider">${[['off','Лише локальна діагностика'],['ollama','Ollama · модель на цьому ПК'],['gemini','Google Gemini · хмарний аналіз']].map(([v,t])=>`<option value="${v}" ${S.settings.aiProvider===v?'selected':''}>${t}</option>`).join('')}</select></div>${field('aiModel','Назва моделі','Точна назва з Ollama або Google AI Studio','text','Ollama: модель має бути вже завантажена. Лаунчер підключається до 127.0.0.1:11434.')}</div><div class="field"><label for="gemini-key">Gemini API key</label><input id="gemini-key" name="geminiKey" type="password" autocomplete="off" placeholder="Власний ключ, якщо обрано Gemini"><small>Зберігається у Windows Credential Manager. Порожнє поле залишає збережений ключ.</small><label class="clear-key"><input name="clearGeminiKey" type="checkbox"> Видалити збережений ключ</label></div></div><div class="info-line neutral">${icon('eye')} Перед кожним ШІ-аналізом ти бачиш точний текст звіту. Gemini отримує його після натискання «Надіслати в Gemini»; застосовуються умови та ліміти твого API-акаунту. Поради не виконуються автоматично.</div></section>`;
}
function reportModal() {
  const d=S.diagnostics||{}, provider=S.settings.aiProvider, model=S.settings.aiModel;
  return `<p class="muted">Відомі токени, email та особисті шляхи приховано. Перевір текст перед передаванням: довільні моди можуть записувати власні приватні дані.</p><p class="report-source">${provider==='gemini'?'Одержувач: Google Gemini':provider==='ollama'?'Одержувач: Ollama на цьому ПК':'ШІ-сервіс не обрано'} · ${esc(model||'модель не вказана')}</p><pre class="report-preview">${esc(d.preview||'Спочатку запусти локальну діагностику.')}</pre><div class="assistant-actions"><button class="btn primary" data-send-report="${esc(d.id||'')}" data-provider="${esc(provider)}" data-model="${esc(model||'')}" ${!d.hasLogs||S.job.busy||!model||!['gemini','ollama'].includes(provider)?'disabled':''}>${icon('sparkles')} ${provider==='gemini'?'Надіслати в Gemini':'Аналізувати в Ollama'}</button><button class="btn" data-dismiss="true">Закрити</button></div>`;
}
document.addEventListener('click',async event=>{
  const el=event.target.closest('[data-send-report]');
  if(!el)return;
  const result=await call('ai',{consent:true,reportId:el.dataset.sendReport,provider:el.dataset.provider,model:el.dataset.model});
  if(result){$('#modal').close();go('logs');}
});
